export const ContentType = {
    playVideoIntro: 'play_video_intro',
    jump: 'pular',
    continue: 'continuar',
    products: 'produtos',
    cup: 'copa',
    theClub: 'o_clube',
    logIn: 'entrar',
    register: 'cadastrar',
    Registered: 'cadastrado',
    logged: 'logado',
    bookNow: 'reservar_agora',
    makePartOfClub: 'faca_parte_do_clube',
    like: 'favorito',
    unlike: 'desfavoritar',
    payment: 'realizar_pagamento',
    saveCard: 'salvar_cartao',
    playVideoSobre: 'play_video_sobre',
}

export const ScreenName = {
    landingPageIntro: 'page_intro',
    sign: 'page_sign',
    signUp: 'page_sign_up',
    signIn: 'page_sign_in',
    dashboard: 'page_dashboard',
    planScreen: 'page_plan_screen',
    checkoutPlan: 'page_checkout_plan',
    docs: 'page_docs',
    video: 'page_video',
    detailHotel: 'page_detail_hotel',
    detailPackages: 'page_detail_packages'
}

export const EventType = {
    selectContent: 'select_content',
    viewPromotion: 'view_promotion',
    purchase: 'purchase'
}

export const ScreenView = {
    Intro: 'intro',
    Sign: 'sign',
    SignIn: 'signIn',
    SignUp: 'signUp',
    Preferences: 'preferences',
    RecoverPassword: 'recover_password',
    TermsConditions: 'terms_conditions',
    PrivacyPolicy: 'privacy_policy',
    ConfirmEmail: 'confirm_email',
    GetLocation: 'get_location',
    VideoScreen: 'video_screen',
    Dashboard: 'dashboard',
    DetailsPackages: 'details_packages',
    DetailsHotels: 'details_hotels',
    DetailsContractedPackages: 'details_contracted_packages',
    NewsTravelers: 'news_travelers',
    Wallet: 'wallet',
    CheckoutPlan: 'checkout_plan',
    HiringHotelDetails: 'hiring_hotel_details',
    Contact: 'contact',
    Alert: 'alert',
    CongratulationPlan: 'congratulation_plan',
    PaymentHistory: 'payment_history',
    Scheduling: 'scheduling',
    HotelScheduling: 'hotel_scheduling',
    MyReservations: 'my_reservations',
    HiringPackageDetails: 'hiring_package_details',
    CongratulationPackage: 'congratulation_package',
    CongratulationHotel: 'congratulation_hotel',
    PlanScreen: 'plan_screen',
    ConfirmReservation: 'confirm_reservation',
    About: 'about',
    Benefits: 'benefits',
    Docs: 'docs',
    Escorts: 'escorts',
    DetailsEscort: 'detailsEscort',
    NewEscort: 'new_escort',
    Favorites: 'favorites',
    MyAccount: 'my_account',
    MyPlan: 'my_plan',
    MenuScreen: 'menu_screen',
    
}
